
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minigateway
spec:
  selector:
    matchLabels:
      app: minigateway
  replicas: 1
  template:
    metadata:
      labels:
        app: minigateway

    spec:
      containers:
      - name: minigateway
        image: ${REPOSITORY_TAG}
        resources:
          requests:
            memory: 200Mi
            cpu: 50m

---

apiVersion: v1
kind: Service

metadata:
  name: minigateway

spec:
  selector:
    app: minigateway

  ports:
    - name: http
      port: 8080
     



  type:  ClusterIP
